theme: minima

title: Deborishi's Dev Sec Ops Page

author: Deborishi Ganguly

description: This a Tech Blog for DevSecOps, QML, AI/ML and many things more!

header_pages:
  - about.md
  - Publications.md
  - teaching.md
  - game.md
  - index.md
  - images.md
